[tool.bandit]
exclude_dirs = ["tests", ".git", "__pycache__", "logs", ".pytest_cache"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.mypy]
exlude = [
    "__pycache__",
    ".pytest_cache",
    ".git",
    "logs",
    "tests"
]

[tool.pylint]
ignore-paths = [
    "__pycache__",
    ".pytest_cache",
    ".git",
    "logs",
    "tests"
]
max-line-length = 88
jobs = 0
load-plugins = [
    "pylint.extensions.confusing_elif",
    "pylint.extensions.for_any_all",
    "pylint.extensions.bad_builtin",
    "pylint.extensions.check_elif",
    "pylint.extensions.redefined_variable_type",
    "pylint.extensions.docparams"
]
