name: security

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "*" ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run mypy
        run: |
          bandit -c pyproject.toml
