name: test

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "*" ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: |
          pytest -c setup.cfg .
