name: test

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "**" ]  # One asterisk only matches branches not containing a '/'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run pytest
        run: |
          pipenv run pytest -c setup.cfg
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.lcov
